name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: GuardioChatbot.sln
      Test_Project_Path: GuardioChatbot.Tests/GuardioChatbot.Tests.csproj
      Wap_Project_Directory: GuardioChatbot.Package
      Wap_Project_Path: GuardioChatbot.Package/GuardioChatbot.Package.wapproj
      Certificate_File: GitHubActionsWorkflow.pfx

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Execute unit tests
      run: dotnet test --configuration ${{ matrix.configuration }}

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Decode the signing certificate
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path $env:Wap_Project_Directory -ChildPath $env:Certificate_File
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - name: Create the app package
      run: |
        msbuild $env:Wap_Project_Path `
          /p:Configuration=${{ matrix.configuration }} `
          /p:UapAppxPackageBuildMode=StoreUpload `
          /p:AppxBundle=Always `
          /p:AppxBundlePlatforms="x86|x64" `
          /p:PackageCertificateKeyFile=$env:Certificate_File `
          /p:PackageCertificatePassword="${{ secrets.Pfx_Key }}"

    - name: Remove the signing certificate
      if: always()
      run: |
        $certPath = Join-Path -Path $env:Wap_Project_Directory -ChildPath $env:Certificate_File
        if (Test-Path $certPath) { Remove-Item -Path $certPath -Force }

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package - ${{ matrix.configuration }}
        path: ${{ env.Wap_Project_Directory }}\AppPackages
        retention-days: 30
